language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: DjChhKxtVphAC/s+heEPT77vyhiRH0WgEOYLns/KAz+cML2o4WtBQAidtWPnk6REa6lKbwmvymg9R/CFHPu8FUJVb7a2+A+hEqY9NKGiyQoQjNJbqRieViHlV1eD08mtLBeVkeUhbh+aXuQicm98x1yoiU/Fp2I839cJ76Nz6L4=
  app: davglass-hack
  on:
    repo: davglass/hack
